### ISSUE TITLE
bracket in search term not ignored in query construction

### ISSUE THREAD

**Issue by torvista** [lat9/prioritize_matching_names#2]
I eventually figured out this was also installed in combination with POSM 
https://github.com/lat9/products_options_stock/issues/229

and found the same issue. 
With this nasty as a search term, 

LP0060BK'nvOpzp; AND 1=1 OR ('"iKO)),&

the opening bracket was in the IF clause (the double quotes and the rest get thrown away) and unbalanced the Select section in addition to the unbalanced query in POSM!

So here also:
```
case '(':
case ')':
case 'and':
case 'or':
```
to
```
case '(':
case ')':
break;
case 'and':
case 'or':
```
cures it.

**Comment by lat9** [comment]
I'll take this a step further, using the `zen_build_keyword_where_clause` function, if defined.
