### ISSUE TITLE
plugin not working with Zen Cart 2.0.1

### ISSUE THREAD

**Issue by lucus-lee** [lat9/prioritize_matching_names#4]
Seems this plugin is not working under zc 2.0.1. Do you have any plans to upgrade it?

**Comment by lat9** [comment]
I have plans to update it.  I'll note that "not working" needs a bit more description.

**Comment by lucus-lee** [comment]
It appears that the issue lies with the following global variables: $search_keywords, $keywords, and $select_str. 
These variables are not receiving values from class.search.php

**Comment by lat9** [comment]
Yep, the search is implemented via a class as of zc200, so those global variables are no longer present.

**Comment by lat9** [comment]
@lucus-lee, please validate that the correction I just posted does, in fact, correct this issue.

**Comment by lucus-lee** [comment]
Thanks, the updated version works.

**Comment by lat9** [comment]
I keep issues open until released, just as a clue to myself!
